CREATE VIEW v_UserRubricTopic
AS

SELECT t.ID_TOPIC, t.ID_RUBRIC, r.NAME_RUBRIC, t.TITLE_TOPIC, t.DESC_TOPIC, u.USER_LOGIN, t.DATE_CREATION
FROM TOPIC t join RUBRIC r on t.ID_RUBRIC = r.ID_RUBRIC
             join RTFFUSER u on u.ID_USER = t.ID_USER;