SELECT COUNT(ID_TOPIC), ID_TOPIC, ID_RUBRIC, DESC_TOPIC, TITLE_TOPIC, USER_LOGIN, DATE_CREATION FROM v_forum
GROUP BY  ID_TOPIC, TITLE_TOPIC, DESC_TOPIC, DATE_CREATION, ID_RUBRIC, USER_LOGIN
HAVING   COUNT(ID_TOPIC) > 1;